/**
 * Self-generated conversation corpus (§32 scenarios, reduced to what M1 can
 * honestly test).
 *
 * Written by hand rather than generated by a model, so the corpus is
 * reproducible and the expectations are falsifiable: every scenario states what
 * must be true of the *behaviour*, not of any particular wording (§51:
 * 模型测试验证结构与行为，不是字符串相等).
 */

export interface ScenarioTurn {
  readonly user: string;
  /** §13: the first turn is addressed; later turns rely on the open session. */
  readonly addressed?: boolean;
  /** Assert the engine refuses this turn (TV audio, quiet mode). */
  readonly expectRejected?: boolean;
  /** Do not call the model for this turn (used with expectRejected). */
  readonly expectReason?: string;
}

export interface Scenario {
  readonly id: string;
  readonly description: string;
  readonly personality?: Readonly<Record<string, number>>;
  readonly turns: readonly ScenarioTurn[];
  readonly expectations: {
    readonly minAccepted?: number;
    readonly minSpeaks?: number;
    readonly allowSilence?: boolean;
    readonly rejectedTurns?: number;
    readonly requireContinuity?: boolean;
  };
}

const WEATHER_PROMPTS = ['西西，明天天气怎么样？', '那后天呢？', '要是下雨我就不去了'];

export const CORPUS: readonly Scenario[] = Object.freeze([
  {
    id: 'weather-thread',
    description: '连续三轮：首句唤醒，之后靠已开启的会话继续，不需要再喊名字',
    turns: [{ user: WEATHER_PROMPTS[0], addressed: true }, { user: WEATHER_PROMPTS[1] }, { user: WEATHER_PROMPTS[2] }],
    expectations: { minAccepted: 3, minSpeaks: 2, allowSilence: true, requireContinuity: true },
  },
  {
    id: 'tired-then-sleepy',
    // Deliberately time-agnostic: an earlier version assumed it was evening, and
    // the model correctly pointed out the real time instead, which the judge then
    // flagged as a contradiction. The scenario must not assert a clock it does not
    // control — only the corpus's *behaviour* expectations should be fixed.
    description: '疲惫与收尾：允许西西选择沉默，也允许很短的回应',
    turns: [{ user: '今天真累。', addressed: true }, { user: '嗯。' }, { user: '我先去歇会儿，回头再聊。' }],
    expectations: { minAccepted: 3, minSpeaks: 1, allowSilence: true },
  },
  {
    id: 'town-trip-thread',
    description: '跨轮次的话题延续：第三轮应当接得住「去镇上」这件事',
    turns: [
      { user: '明天下午我去镇上办点事。', addressed: true },
      { user: '你说要带伞吗？' },
      { user: '我回来了，事情办完了。' },
    ],
    expectations: { minAccepted: 3, minSpeaks: 3, requireContinuity: true },
  },
  {
    id: 'tv-not-addressed',
    description: '电视在说话但没有叫西西：整轮都要被拒绝，且不写入会话历史',
    turns: [{ user: '明天天气怎么样？', addressed: false, expectRejected: true, expectReason: 'REJECTED_NOT_ADDRESSED' }],
    expectations: { rejectedTurns: 1 },
  },
  {
    id: 'quiet-mode',
    description: '「今天安静点」之后，即使叫名字也不接话',
    turns: [
      { user: '西西，今天我想安静点。', addressed: true },
      { user: '西西，在吗？', addressed: true, expectRejected: true, expectReason: 'REJECTED_SUSPENDED' },
    ],
    expectations: { minAccepted: 1, rejectedTurns: 1 },
  },
  {
    id: 'terse-personality',
    description: '低 verbosity / 低 talkativeness：回答应当明显更短',
    personality: { verbosity: 0.1, talkativeness: 0.2, curiosity: 0.1 },
    turns: [{ user: '西西，明天天气怎么样？', addressed: true }, { user: '那后天呢？' }, { user: '你最近怎么样？' }],
    expectations: { minAccepted: 3, minSpeaks: 1, allowSilence: true },
  },
  {
    id: 'chatty-personality',
    description: '高 verbosity / 高 talkativeness：同样的问句应当说得更多',
    personality: { verbosity: 0.95, talkativeness: 0.9, curiosity: 0.85 },
    turns: [{ user: '西西，明天天气怎么样？', addressed: true }, { user: '那后天呢？' }, { user: '你最近怎么样？' }],
    expectations: { minAccepted: 3, minSpeaks: 2, allowSilence: true },
  },
  {
    id: 'silence-allowed',
    description: '连续应和：西西应当有权不说话，而不是硬找话说',
    turns: [{ user: '嗯。', addressed: true }, { user: '哦。' }],
    expectations: { minAccepted: 2, allowSilence: true },
  },
]);

/** Phrases that mean the reply leaked prompt scaffolding or broke character. */
export const FORBIDDEN_PATTERNS: readonly { readonly pattern: RegExp; readonly why: string }[] = [
  { pattern: /有效人格|提示词|系统提示|system prompt/i, why: '把运行时上下文说给用户听了' },
  { pattern: /(作为|我是).{0,6}(AI|人工智能|语言模型|助手)/i, why: '自称 AI/助手，破坏陪伴角色' },
  { pattern: /\bassistant\b|\bas an AI\b/i, why: '英文的助手腔' },
  { pattern: /(代码|仓库|文件系统|模型参数|API)/, why: '提到了实现细节' },
  { pattern: /有什么(可以|能)帮(您|你)(的)?吗/, why: '客服腔' },
];
