/**
 * `@xixi/conversation` — the deterministic half of a conversation: the state
 * machine that decides whether a turn is accepted (§12/§13), the prompt
 * assembly that decides what the model sees (§26), and the engine that ties
 * them to the adapter and the event log.
 */
export {
  CLOCK_TOLERANCE_MINUTES,
  ConversationEngine,
  findUnbackedFactClaims,
  UNBACKED_FACT_REPLY,
  type ConversationEngineOptions,
  type ConversationTurn,
  type ReplyHygieneSummary,
  type ReplySegmentPlayback,
  type RespondHooks,
  type RespondInput,
  type SilenceReason,
  type UnbackedFactClaim,
} from './engine.ts';
export {
  ConversationStateMachine,
  DEFAULT_FSM_CONFIG,
  type ConversationState,
  type FsmConfig,
  type FsmSnapshot,
  type TurnAcceptance,
  type TurnAcceptanceReason,
} from './fsm.ts';
export {
  CORE_IDENTITY,
  describeTimeOfDay,
  HARD_POLICY,
  personalityDirectives,
  PromptAssembler,
  SILENCE_TOKEN,
  worldStateLite,
  type AssembleInput,
  type AssembledPrompt,
  type MoodContext,
  type PromptTurn,
  type WorldStateLite,
} from './prompt.ts';
export { DEFAULT_SILENCE_TOLERANCE, moodToleranceScale } from './personality.ts';
export {
  normalizeReplyText,
  REPLY_LIMITS,
  resolveReplyLimits,
  splitReplyIntoSegments,
  type ReplySegmentOptions,
  type SegmentedReply,
} from './segments.ts';
export {
  DEFAULT_EXTRACTION_SCHEDULER,
  TurnMemoryExtractor,
  type ExtractionResult,
  type ExtractionScheduler,
  type PostTurnJob,
  type TurnMemoryExtractorOptions,
} from './extractor.ts';
export {
  EXPLICIT_FEEDBACK_WEIGHT,
  FEEDBACK_RULES,
  INFERRED_FEEDBACK_WEIGHT,
  interpretFeedback,
  interpretFeedbackInput,
  interpretInference,
  type FeedbackInterpretation,
  type FeedbackKind,
  type FeedbackRule,
} from './feedback-interpreter.ts';
export {
  classifyThreadAnswer,
  DEFAULT_TOPIC_ENGINE_SETTINGS,
  extractOpenThreads,
  followUpHintFor,
  openThreadFollowUpComponents,
  parseTopicEngineSettings,
  TOPIC_SOURCES,
  TopicEngine,
  type ExtractOpenThreadInput,
  type OpenThreadFollowUp,
  type OpenThreadView,
  type ReconcileResult,
  type ThreadAnswerKind,
  type TopicCandidate,
  type TopicEngineOptions,
  type TopicEngineSettings,
  type TopicEngineStatus,
  type TopicSource,
} from './topic-engine.ts';
export {
  readTopicHistory,
  TopicHistory,
  topicOfferedWithin,
  topicOutcome,
  type TopicHistoryEntry,
} from './topic-history.ts';
export {
  DEFAULT_PROACTIVE_SETTINGS,
  DEFAULT_PROACTIVITY,
  deriveProactiveSignals,
  evaluateProactiveGates,
  initiativeKindForTrigger,
  isWithinQuietHours,
  localDayOf,
  localMinutesOf,
  normalizeModelReasonCode,
  parseClockMinutes,
  parseProactiveSettings,
  proactiveBasis,
  proactiveThreshold,
  PROACTIVE_INITIATIVE_KINDS,
  PROACTIVE_INITIATIVE_LABELS,
  PROACTIVE_KNOWN_REASON_CODES,
  PROACTIVE_MODEL_REASON_CODES,
  PROACTIVE_MODEL_REASON_LABELS,
  PROACTIVE_PRIMARY_SIGNALS,
  PROACTIVE_REASON_CODES,
  PROACTIVE_RETIRED_REASON_CODES,
  PROACTIVE_SCORE_WEIGHTS,
  PROACTIVE_SIGNALS,
  PROACTIVE_SIGNAL_LABELS,
  PROACTIVE_TRIGGERS,
  ProactiveEngine,
  readProactiveConsultations,
  readProactiveHistory,
  readUserTurnTimes,
  scoreProactiveCandidate,
  type ProactiveCandidate,
  type ProactiveConsiderInput,
  type ProactiveDecider,
  type ProactiveDelivery,
  type ProactiveDeliveryRecord,
  type ProactiveEngineOptions,
  type ProactiveGateContext,
  type ProactiveGateResult,
  type ProactiveInitiativeKind,
  type ProactiveModelDecision,
  type ProactiveModelInput,
  type ProactiveModelReasonCode,
  type ProactiveOutcome,
  type ProactivePrimarySignal,
  type ProactiveReasonCode,
  type ProactiveRetiredReasonCode,
  type ProactiveSettings,
  type ProactiveSignal,
  type ProactiveSignalsView,
  type ProactiveTrigger,
} from './proactive.ts';
