/**
 * `@xixi/domain` — Xixi's durable state: event log, sessions, personality
 * baseline. This is the only package that opens SQLite.
 */
export { type Clock, fixedClock, systemClock } from './clock.ts';
export {
  DEFAULT_TOOL_APPROVAL_SETTINGS,
  TOOL_APPROVAL_REASON_CODES,
  TOOL_APPROVAL_STATUSES,
  ToolApprovalStore,
  approvalExpiry,
  parseToolApprovalSettings,
  type NewToolApproval,
  type ToolApproval,
  type ToolApprovalChange,
  type ToolApprovalQuery,
  type ToolApprovalReasonCode,
  type ToolApprovalSettings,
  type ToolApprovalStatus,
  type TransitionToolApprovalOptions,
} from './approvals.ts';
export { loadXixiConfig, parseXixiConfig, type XixiConfig } from './config.ts';
export {
  DEFAULT_PLUGIN_SETTINGS,
  MCP_SERVER_NAME_MAX_CHARS,
  MCP_TIMEOUT_MS_MAX,
  MCP_TIMEOUT_MS_MIN,
  parsePluginSettings,
  type PluginHttpMcpServer,
  type PluginMcpRisk,
  type PluginMcpServerSetting,
  type PluginMcpTransportKind,
  type PluginNewsSetting,
  type PluginNewsSourceSetting,
  type PluginSettings,
  type PluginStdioMcpServer,
} from './plugin-settings.ts';
export { DomainError, type DomainErrorCode } from './errors.ts';
export {
  assertNewReminder,
  buildReminderEvent,
  DEFAULT_REMINDER_SETTINGS,
  formatZonedIso,
  instantFromWallClock,
  newReminderId,
  parseReminderSettings,
  parseSpokenNumber,
  REMINDER_NEXT_STATUSES,
  REMINDER_REASON_CODES,
  REMINDER_RESOLVE_KINDS,
  REMINDER_STATUSES,
  reminderIsDue,
  reminderPayload,
  reminderReasonForStatus,
  reminderTransitionAllowed,
  ReminderStore,
  resolveReminderWhen,
  UNKNOWN_REMINDER_OWNER,
  zoneOffsetMinutes,
  zonedWallClock,
  type NewReminder,
  type Reminder,
  type ReminderChange,
  type ReminderQuery,
  type ReminderReasonCode,
  type ReminderResolveKind,
  type ReminderSettings,
  type ReminderStatus,
  type ReminderWhenContext,
  type ReminderWhenResolution,
  type TransitionReminderOptions,
  type ZonedWallClock,
} from './reminders.ts';
export {
  isFollowUpDue,
  normalizeThreadSummary,
  OPEN_THREAD_ACTIVE_STATUSES,
  OPEN_THREAD_SETTLED_STATUSES,
  OPEN_THREAD_STATUSES,
  OpenThreadStore,
  threadIdFromSourceEvent,
  type NewOpenThread,
  type OpenThread,
  type OpenThreadChange,
  type OpenThreadQuery,
  type OpenThreadStatus,
  type TransitionOpenThreadOptions,
} from './open-threads.ts';
export { appliedMigrations, listMigrationFiles, migrate, type AppliedMigration, type MigrationFile } from './migrations.ts';
export {
  ACTIVE_MEMORY_STATUSES,
  MEMORY_SOURCE_CONFIDENCE,
  MEMORY_SOURCE_TYPES,
  MEMORY_STATUSES,
  MemoryStore,
  RELATIONSHIP_ANSWER_WINDOW_MINUTES,
  type EpisodicKind,
  type EpisodicMemory,
  type MemoryQuery,
  type MemorySourceType,
  type MemoryStatus,
  type MemoryStatusChange,
  type NewEpisodicMemory,
  type NewRelationshipNote,
  type NewSemanticMemory,
  type RelationshipNote,
  type RelationshipSnapshot,
  type SemanticMemory,
} from './memory.ts';
export {
  DEFAULT_SELF_MODEL_SETTINGS,
  effectivePersonality,
  localDayOf,
  NEUTRAL_PROFILE_VALUE,
  parseSelfModelSettings,
  SELF_MODEL_SOURCES,
  SELF_MODEL_SOURCE_WEIGHTS,
  SelfModel,
  type LearnedDelta,
  type LearnedDeltaInput,
  type LearnedDeltaResult,
  type SelfModelSettings,
  type SelfModelSource,
  type SessionOverride,
  type SessionOverrideInput,
} from './self-model.ts';
export {
  applyMoodDecay,
  applyMoodDelta,
  applyMoodSignals,
  applyTimeOfDay,
  clampMood,
  clampMoodValue,
  classifyMoodSignal,
  DEFAULT_MOOD_SETTINGS,
  describeMoodSignal,
  MOOD_BAND_THRESHOLDS,
  MOOD_BOUNDS,
  MOOD_SIGNAL_CODES,
  MOOD_SIGNALS,
  moodBand,
  moodBias,
  moodProse,
  moodStateProse,
  moodToneLines,
  NEUTRAL_MOOD,
  parseMoodSettings,
  TIME_OF_DAY_PULL_PER_HOUR,
  timeOfDayMoodTarget,
  type MoodApplication,
  type MoodBand,
  type MoodSettings,
  type MoodSignal,
  type MoodSignalCode,
  type MoodSignalSpec,
  type MoodState,
} from './mood.ts';
export {
  MOOD_PROACTIVITY_NUDGE,
  MOOD_TONE_SPAN,
  MoodEngine,
  moodBiasOf,
  moodProactivityNudge,
  moodToneScale,
  type MoodBeatResult,
  type MoodEngineOptions,
} from './mood-engine.ts';
export {
  clampPersonality,
  PERSONALITY_PROPERTIES,
  personalityProperty,
  type PersonalityProperty,
} from './personality.ts';
export {
  CANONICAL_DATA_DIR,
  CANONICAL_DATA_DIR_ENV,
  CANONICAL_STORE_ENTRIES,
  DEFAULT_DATA_DIR,
  DEFAULT_DB_FILE,
  DEFAULT_PRESENCE_TTL_SECONDS,
  MOOD_STATE_KEY,
  openXixiStore,
  PRESENCE_KEY,
  resolveCanonicalDataDir,
  XixiStore,
  type MoodChange,
  type ReadEventsQuery,
  type RecordMoodInput,
  type RecordPresenceInput,
  type RecordTurnInput,
  type SelfProfileChange,
  type SelfProfileEntry,
  type SessionRecord,
  type SetWorldStateInput,
  type StoredEvent,
  type StoredMood,
  type StoreOptions,
  type TurnAction,
  type TurnRecord,
  type TurnRole,
  type WorldState,
  type WorldStateEntry,
  type WorldStateQuery,
} from './store.ts';
