"""Offline regression tests for the presence detector (M6).

Run them with either interpreter:

    E:\\worker2\\.venvs\\cv4\\Scripts\\python.exe -m unittest discover -s tests/perception -t tests/perception -v
    npm test        # the TypeScript wrapper in tests/perception/camera-presence.test.ts runs exactly that

Everything here is offline and deterministic: frames are drawn by
`perception_edge.scenes` (no external images, no licence questions), timestamps are
synthetic, and no test touches the camera or the network. Real-camera behaviour is a
separate, explicit step: `node scripts/verify-camera-presence.ts`.

Image sources: **all frames are generated by code** - see `perception_edge/scenes.py`. Two
optional positive controls (a group selfie and `lena.jpg`) exist under `data/models/`, are
not tracked by git and are not required by these tests; when present they are exercised by
`test_optional_external_positive_control`.
"""

from __future__ import annotations

import json
import sys
import unittest
from pathlib import Path

import cv2
import numpy as np

# Allow running this file directly (python tests/perception/test_presence.py) as well as
# through unittest discovery from the repository root.
PACKAGE_ROOT = Path(__file__).resolve().parents[2] / "services" / "perception-edge"
if str(PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PACKAGE_ROOT))

from perception_edge.camera import (  # noqa: E402
    CameraConfig,
    backend_name,
    default_backend,
    negotiated_fourcc,
)
from perception_edge.contracts import (  # noqa: E402
    EVENT_ID_PATTERN,
    TIMESTAMP_PATTERN,
    build_presence_event,
    validate_presence_event,
)
from perception_edge.debounce import (  # noqa: E402
    ABSENT,
    PRESENT,
    DebounceConfig,
    PresenceDebouncer,
)
from perception_edge.detector import (  # noqa: E402
    DEFAULT_FACE_SCORE_THRESHOLD,
    NullFaceDetector,
    YuNetFaceDetector,
    load_yunet_model_path,
)
from perception_edge.emitter import EVENTS_INSERT, EventEmitter  # noqa: E402
from perception_edge.run import synthetic_scenario  # noqa: E402
from perception_edge.scenes import (  # noqa: E402
    empty_static,
    empty_with_noise,
    face_track,
    person_track,
    rig_face,
    speckle_frame,
    still_track,
)
from perception_edge.selftest import detect_script, face_backend_available, run_script  # noqa: E402
from perception_edge.semantic import (  # noqa: E402
    SemanticAnalysisHook,
    SemanticAnalysisNotImplemented,
    describe_privacy_boundary,
)

FIELD_THRESHOLDS = {
    "present_confirm_frames": 15,
    "absent_confirm_frames": 45,
    "release_grace_ms": 3000.0,
}


class SceneTests(unittest.TestCase):
    """The fixtures must behave as documented, otherwise every other test is meaningless."""

    def test_empty_scene_has_no_motion(self) -> None:
        signals = detect_script(still_track(6), detector="none")
        self.assertTrue(all(not signal.motion for signal in signals[1:]))
        self.assertEqual([round(s.motion_ratio, 5) for s in signals[1:]], [0.0] * 5)

    def test_person_scene_produces_motion(self) -> None:
        signals = detect_script(person_track(12, step=14), detector="none")
        moved = [signal for signal in signals[1:] if signal.motion]
        self.assertEqual(len(moved), 11, "the walking figure must be motion on every consecutive pair")
        self.assertGreater(max(signal.motion_ratio for signal in moved), 0.005)

    def test_gaussian_noise_alone_is_not_motion(self) -> None:
        """Sensor noise is not a person: with the measured field threshold, noise stays quiet."""
        frames = [(empty_with_noise(seed=index), index * 33.0) for index in range(8)]
        signals = detect_script(frames, detector="none")
        self.assertTrue(all(not signal.motion for signal in signals[1:]))


class MotionGateTests(unittest.TestCase):
    def test_motion_threshold_ignores_noise_and_catches_edges(self) -> None:
        """A 1-grey-level global change must not gate, a 40-level change must."""
        base = empty_static()
        faint = np.clip(base.astype(np.int16) + 1, 0, 255).astype(np.uint8)
        strong = np.clip(base.astype(np.int16) + 40, 0, 255).astype(np.uint8)
        faint_signals = detect_script([(base, 0.0), (faint, 33.0)], detector="none")
        strong_signals = detect_script([(base, 0.0), (strong, 33.0)], detector="none")
        self.assertFalse(faint_signals[1].motion)
        self.assertTrue(strong_signals[1].motion)

    def setUp(self) -> None:
        # These use the Haar backend because it needs no model file; on OpenCV 5 it does not
        # exist, so the detector construction raises. Skip instead of silently passing.
        if not face_backend_available("haar"):
            self.skipTest("Haar unavailable: OpenCV 5.0 removed cv2.CascadeClassifier")

    def test_speckle_frame_moves_but_is_a_single_frame(self) -> None:
        frames = still_track(21)
        frames[10] = (speckle_frame(), frames[10][1])
        signals = detect_script(frames, detector="haar")
        # A corrupted frame is motion-like on both of its transitions (into, and back out
        # of, the corruption) - and then the scene is quiet again.
        self.assertTrue(signals[10].motion)
        self.assertTrue(signals[11].motion, "the second transition, back to a clean frame")
        self.assertFalse(any(signal.motion for signal in signals[12:]))


class FaceConfirmationTests(unittest.TestCase):
    """The confirmation path. Skipped - loudly - when the interpreter cannot provide it."""

    def setUp(self) -> None:
        if not face_backend_available("haar"):
            self.skipTest("Haar unavailable: OpenCV 5.0 removed cv2.CascadeClassifier")

    def test_empty_room_never_reports_a_face(self) -> None:
        from perception_edge.detector import HaarFaceDetector

        detector = HaarFaceDetector()
        self.assertEqual(detector.detect(empty_static()), 0)
        self.assertEqual(detector.detect(speckle_frame()), 0, "noise must not become a face")

    def test_face_detection_is_skipped_between_confirmations(self) -> None:
        signals = detect_script(person_track(12), detector="haar", face_every_n_frames=5)
        ran = [signal.frame_index for signal in signals if signal.face_ran]
        self.assertEqual(ran, [0, 5, 10])

    def test_backend_failure_never_becomes_a_person(self) -> None:
        class BrokenDetector(NullFaceDetector):
            name = "broken"

            def detect(self, frame):  # noqa: ANN001, ANN201
                raise RuntimeError("simulated backend failure")

        from perception_edge.detector import DetectionConfig, PresenceDetector

        engine = PresenceDetector(DetectionConfig(), BrokenDetector())
        signals = engine.detect(empty_static(), 0.0)
        self.assertFalse(signals.signal)
        self.assertEqual(signals.faces, 0)


class DebounceTests(unittest.TestCase):
    """Hysteresis: the parameters and the reasons live in perception_edge/debounce.py."""

    def test_one_frame_of_evidence_does_not_flip_the_state(self) -> None:
        debouncer = PresenceDebouncer(
            DebounceConfig(present_confirm_frames=3, absent_confirm_frames=2, minimum_evidence_ms=100.0)
        )
        self.assertEqual(debouncer.state, ABSENT)
        first = debouncer.update(signal=True, motion_ratio=0.02, faces=0, timestamp_ms=0.0, frame_index=0)
        self.assertFalse(first.changed, "one frame of evidence must not flip the state")
        confirmations = []
        for index, timestamp in enumerate((100.0, 200.0, 300.0), start=1):
            decision = debouncer.update(signal=True, motion_ratio=0.02, faces=0, timestamp_ms=timestamp, frame_index=index)
            if decision.changed:
                confirmations.append((index, decision))
        self.assertEqual(len(confirmations), 1, "the state must flip exactly once")
        index, decision = confirmations[0]
        self.assertEqual(decision.state, PRESENT)
        self.assertEqual(decision.reason, "present_confirmed")
        self.assertEqual(index, 2, "3 consistent frames AND 100 ms of evidence")

    def test_evidence_shorter_than_the_minimum_is_noise(self) -> None:
        """A run shorter than `minimum_evidence_ms` never becomes "present"."""
        debouncer = PresenceDebouncer(
            DebounceConfig(present_confirm_frames=1, absent_confirm_frames=1, minimum_evidence_ms=1000.0)
        )
        debouncer.update(signal=True, motion_ratio=0.02, faces=0, timestamp_ms=0.0, frame_index=0)
        debouncer.update(signal=False, motion_ratio=0.0, faces=0, timestamp_ms=100.0, frame_index=1)
        self.assertEqual(debouncer.state, ABSENT)
        self.assertEqual(debouncer.counters.runs_rejected_as_too_short, 1)
        self.assertEqual(debouncer.counters.last_run_ms, 100.0)

    def test_evidence_longer_than_the_minimum_counts_normally(self) -> None:
        debouncer = PresenceDebouncer(
            DebounceConfig(present_confirm_frames=2, absent_confirm_frames=1, minimum_evidence_ms=1000.0)
        )
        decision = None
        for index, timestamp in enumerate((0.0, 33.0)):
            decision = debouncer.update(signal=True, motion_ratio=0.02, faces=0, timestamp_ms=timestamp, frame_index=index)
        self.assertEqual(decision.state, ABSENT)
        self.assertEqual(decision.reason, "burst_too_short")
        # A run that lasts past the minimum duration (and has enough frames) does confirm.
        confirmations = []
        for index, timestamp in enumerate((1000.0, 1033.0), start=2):
            decision = debouncer.update(signal=True, motion_ratio=0.02, faces=0, timestamp_ms=timestamp, frame_index=index)
            if decision.changed:
                confirmations.append(decision)
        self.assertEqual(len(confirmations), 1)
        self.assertEqual(confirmations[0].state, PRESENT)
        self.assertEqual(confirmations[0].reason, "present_confirmed")

    def test_single_glitch_frame_inside_the_window_is_ignored(self) -> None:
        if not face_backend_available("haar"):
            self.skipTest("Haar unavailable: OpenCV 5.0 removed cv2.CascadeClassifier")
        frames = still_track(20)
        frames[7] = (speckle_frame(), frames[7][1])
        captured = run_script(frames, detector="haar", **FIELD_THRESHOLDS)
        # Only the startup announcement; one bad frame must not produce a transition.
        self.assertEqual(captured.states, [ABSENT])
        self.assertGreaterEqual(captured.summary["counters"]["runs_rejected_as_too_short"], 1)

    def test_short_run_is_ignored_even_when_it_reaches_the_frame_threshold(self) -> None:
        # Four consecutive frames carry evidence: three walking positions plus the
        # transition back to the static scene. 4 frames >= 3, but the run lasts only
        # 100 ms, so it is still not a person.
        frames = still_track(10) + person_track(3, step=25, start_x=60) + still_track(10)
        captured = run_script(frames, detector="none", present_confirm_frames=3, absent_confirm_frames=3)
        self.assertEqual(captured.states, [ABSENT], "启动状态不是一次「变化」")
        self.assertEqual(captured.summary["counters"]["runs_rejected_as_too_short"], 1)
        self.assertEqual(captured.summary["counters"]["last_run_frames"], 4)

    def test_brief_occlusion_does_not_flip_the_state(self) -> None:
        """0.5 s with the lens covered must not produce absent-then-present again."""
        frames = person_track(80, step=14) + still_track(15) + person_track(80, step=14) + still_track(20)
        captured = run_script(frames, detector="none", **FIELD_THRESHOLDS)
        self.assertEqual(
            captured.states,
            [ABSENT, PRESENT],
            "brief coverage must not create an absence event",
        )

    def test_long_occlusion_reports_absence_exactly_once(self) -> None:
        """5 s of nothing *is* an absence - reported once, not repeatedly."""
        frames = person_track(80, step=14) + still_track(150) + person_track(80, step=14) + still_track(160)
        captured = run_script(frames, detector="none", **FIELD_THRESHOLDS)
        self.assertEqual(captured.states, [ABSENT, PRESENT, ABSENT, PRESENT, ABSENT])

    def test_release_grace_gates_absence_even_when_the_blank_window_is_reached(self) -> None:
        debouncer = PresenceDebouncer(
            DebounceConfig(
                present_confirm_frames=1,
                absent_confirm_frames=2,
                release_grace_ms=1000.0,
                minimum_evidence_ms=0.0,
            )
        )
        debouncer.update(signal=True, motion_ratio=0.02, faces=0, timestamp_ms=0.0, frame_index=0)
        self.assertEqual(debouncer.state, PRESENT)
        debouncer.update(signal=False, motion_ratio=0.0, faces=0, timestamp_ms=10.0, frame_index=1)
        decision = debouncer.update(signal=False, motion_ratio=0.0, faces=0, timestamp_ms=20.0, frame_index=2)
        self.assertFalse(decision.changed, "the grace period has not elapsed at 20 ms")
        self.assertEqual(decision.reason, "absent_pending")
        for index in range(3, 60):
            decision = debouncer.update(signal=False, motion_ratio=0.0, faces=0, timestamp_ms=index * 33.0, frame_index=index)
            if decision.changed:
                break
        self.assertTrue(decision.changed)
        self.assertEqual(decision.reason, "absent_confirmed")

    def test_attribution_is_recorded_on_entering_presence(self) -> None:
        """A stale confidence must not leak into the next state change (regression)."""
        debouncer = PresenceDebouncer(DebounceConfig(present_confirm_frames=1, minimum_evidence_ms=0.0))
        entering = debouncer.update(signal=True, motion_ratio=0.01, faces=0, timestamp_ms=0.0, frame_index=0)
        self.assertTrue(entering.changed)
        self.assertEqual(entering.confidence, 0.75, "motion-only arrival")

        face_debouncer = PresenceDebouncer(DebounceConfig(present_confirm_frames=1, minimum_evidence_ms=0.0))
        face_arrival = face_debouncer.update(signal=True, motion_ratio=0.01, faces=1, timestamp_ms=0.0, frame_index=0)
        self.assertEqual(face_arrival.confidence, 0.9, "a confirmed face is stronger evidence than motion")
        self.assertGreater(face_arrival.confidence, entering.confidence)


class ScenarioTests(unittest.TestCase):
    """The named scenarios are the same ones the CLI and the verify script can replay."""

    def test_person_arrives_and_leaves(self) -> None:
        captured = run_script(synthetic_scenario("person-arrives-moves-leaves"), detector="none", **FIELD_THRESHOLDS)
        self.assertEqual(captured.states, [ABSENT, PRESENT, ABSENT])
        self.assertEqual(captured.summary["final_state"], ABSENT)

    def test_empty_room_produces_no_transitions(self) -> None:
        captured = run_script(synthetic_scenario("empty-still"), detector="none", **FIELD_THRESHOLDS)
        self.assertEqual(captured.states, [ABSENT], "空房间只有启动时那一条状态")

    def test_events_are_emitted_only_on_change(self) -> None:
        captured = run_script(synthetic_scenario("long-occlusion"), detector="none", **FIELD_THRESHOLDS)
        self.assertEqual(captured.states, [ABSENT, PRESENT, ABSENT, PRESENT])
        frames_processed = captured.summary["frames"]
        self.assertGreater(frames_processed, len(captured.events) * 50, "一次转换一条事件，不是一帧一条")

    def test_long_occlusion_end_to_end_produces_five_records(self) -> None:
        frames = person_track(80, step=14) + still_track(150) + person_track(80, step=14) + still_track(160)
        captured = run_script(frames, detector="none", **FIELD_THRESHOLDS)
        self.assertEqual(captured.states, [ABSENT, PRESENT, ABSENT, PRESENT, ABSENT])

    def test_startup_announces_the_initial_state_once(self) -> None:
        """The projection must exist from the first second, so the start state is published once."""
        captured = run_script(still_track(5), detector="none", **FIELD_THRESHOLDS)
        self.assertEqual(len(captured.events), 1)
        self.assertEqual(captured.events[0]["payload"]["present"], False)
        self.assertIn("camera_started", captured.events[0]["payload"]["source_detail"])


class ContractTests(unittest.TestCase):
    """The Python producer must build exactly what packages/contracts released."""

    def test_built_event_matches_the_released_schemas(self) -> None:
        event = build_presence_event(_presence_input(present=True))
        validate_presence_event(event)  # raises ContractViolation on any drift
        self.assertEqual(event["schema"], "xixi.event.v1")
        self.assertEqual(event["schema_version"], 1)
        self.assertTrue(EVENT_ID_PATTERN.match(event["event_id"]))
        self.assertTrue(TIMESTAMP_PATTERN.match(event["timestamp"]))
        self.assertFalse(event["timestamp"].endswith("Z"), "the contract rejects Z-form timestamps")
        self.assertEqual(set(event["payload"]), {"present", "source_detail"})

    def test_payload_cannot_carry_extra_keys(self) -> None:
        event = build_presence_event(_presence_input(present=False))
        event["payload"]["extra"] = "should not be allowed"
        with self.assertRaises(Exception):
            validate_presence_event(event)

    def test_source_detail_is_capped_by_the_contract(self) -> None:
        with self.assertRaises(Exception):
            build_presence_event(_presence_input(present=True, source_detail="x" * 201))

    def test_confidence_must_stay_within_the_contract_range(self) -> None:
        with self.assertRaises(Exception):
            build_presence_event(_presence_input(present=True, confidence=1.4))

    def test_event_round_trips_through_stdout_as_json(self) -> None:
        captured = run_script(synthetic_scenario("person-arrives-moves-leaves"), detector="none", **FIELD_THRESHOLDS)
        self.assertEqual(len(captured.events), 3)
        for event in captured.events:
            self.assertEqual(set(event["payload"]), {"present", "source_detail"})
            self.assertIsInstance(event["payload"]["present"], bool)
            json.dumps(event)  # must be JSON-serialisable as-is


class EmitterTests(unittest.TestCase):
    """Writing: stdout always, the event log only when the database is a real Xixi store."""

    def test_append_to_a_missing_database_is_skipped_with_a_reason(self) -> None:
        import tempfile

        emitter = EventEmitter(db_path=Path(tempfile.gettempdir()) / "xixi-does-not-exist.sqlite", append=True)
        self.assertIsNotNone(emitter.stats.db_skipped_reason)
        emitter.close()

    def test_append_requires_a_database_path(self) -> None:
        emitter = EventEmitter(append=True)
        self.assertIn("--append", emitter.stats.db_skipped_reason or "")
        emitter.close()

    def test_insert_statement_matches_the_released_column_list(self) -> None:
        columns = {
            "event_id",
            "event_type",
            "schema_version",
            "timestamp",
            "source",
            "room",
            "actor",
            "confidence",
            "correlation_id",
            "session_id",
            "payload_json",
        }
        self.assertTrue(columns.issubset(set(EVENTS_INSERT.split("(", 1)[1].split(")", 1)[0].replace(" ", "").split(","))))

    def test_append_is_refused_when_the_002_migration_has_not_run(self) -> None:
        """A half-write (event in the log, projection never updated) must not be possible."""
        import sqlite3
        import tempfile

        migrations = Path(__file__).resolve().parents[2] / "packages" / "domain" / "src" / "migrations"
        db_path = Path(tempfile.mkdtemp(prefix="xixi-perception-old-")) / "old.sqlite"
        connection = sqlite3.connect(str(db_path))
        connection.executescript((migrations / "001_initial.sql").read_text(encoding="utf-8"))
        connection.commit()
        connection.close()

        emitter = EventEmitter(db_path=db_path, append=True)
        try:
            self.assertIsNotNone(emitter.stats.db_skipped_reason)
            self.assertIn("world_state", emitter.stats.db_skipped_reason or "")
        finally:
            emitter.close()

    def test_appends_to_an_initialized_database_and_the_row_is_readable(self) -> None:
        import sqlite3
        import tempfile

        migrations = Path(__file__).resolve().parents[2] / "packages" / "domain" / "src" / "migrations"
        db_path = Path(tempfile.mkdtemp(prefix="xixi-perception-")) / "x.sqlite"
        connection = sqlite3.connect(str(db_path))
        for name in ("001_initial.sql", "002_world_state.sql"):
            connection.executescript((migrations / name).read_text(encoding="utf-8"))
        connection.commit()
        connection.close()

        emitter = EventEmitter(db_path=db_path, append=True)
        try:
            emitter.emit_presence(present=True, confidence=0.9, source_detail="test")
            self.assertEqual(emitter.stats.appended_to_db, 1)
        finally:
            emitter.close()

        connection = sqlite3.connect(str(db_path))
        rows = connection.execute("SELECT event_type, payload_json, session_id FROM events").fetchall()
        projection = connection.execute(
            "SELECT key, value, source, updated_at, confidence, ttl_seconds FROM world_state"
        ).fetchall()
        connection.close()
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0][0], "presence.changed")
        self.assertIsNone(rows[0][2], "presence is not part of a conversation session")
        self.assertEqual(json.loads(rows[0][1])["present"], True)
        # The projection is written in the same transaction, so it cannot lag behind.
        self.assertEqual(len(projection), 1)
        self.assertEqual(projection[0][0], "presence.home")
        self.assertEqual(projection[0][1], "present")
        self.assertEqual(projection[0][2], "perception.laptop_camera")
        self.assertEqual(projection[0][5], 60.0)


class PrivacyBoundaryTests(unittest.TestCase):
    """No upload path, and semantic analysis is a stub - asserted, not promised."""

    def test_semantic_hook_is_not_implemented(self) -> None:
        hook = SemanticAnalysisHook()
        hook.on_presence_changed(True, empty_static())
        with self.assertRaises(SemanticAnalysisNotImplemented):
            hook.capture_snapshot(empty_static())
        self.assertFalse(hook.status()["implemented"])
        self.assertEqual(hook.status()["uploads"], 0)

    def test_enabling_the_hook_raises_instead_of_calling_out(self) -> None:
        hook = SemanticAnalysisHook(enabled=True)
        with self.assertRaises(SemanticAnalysisNotImplemented):
            hook.on_presence_changed(True, empty_static())

    def test_no_network_imports_and_no_torch_in_the_service(self) -> None:
        import ast

        banned = {"requests", "httpx", "urllib", "urllib3", "socket", "http", "aiohttp", "websockets", "torch"}
        offenders: list[str] = []
        for path in sorted((PACKAGE_ROOT / "perception_edge").glob("*.py")):
            tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
            for node in ast.walk(tree):
                names: list[str] = []
                if isinstance(node, ast.Import):
                    names = [alias.name.split(".")[0] for alias in node.names]
                elif isinstance(node, ast.ImportFrom) and node.module:
                    names = [node.module.split(".")[0]]
                for name in names:
                    if name in banned:
                        offenders.append(f"{path.name}:{name}")
        self.assertEqual(offenders, [], "no network client and no torch anywhere in the service")

    def test_privacy_summary_states_no_upload(self) -> None:
        summary = describe_privacy_boundary()
        self.assertTrue(summary["local_only"])
        self.assertFalse(summary["video_uploaded"])
        self.assertEqual(summary["stills_uploaded"], 0)


class OptionalExternalPositiveControlTests(unittest.TestCase):
    """Optional: external images kept locally for spot checks. Never required, never uploaded.

    `data/models/largest_selfie.jpg` and `data/models/lena.jpg` were fetched during the T0
    recon into `data/` (which is git-ignored); they are **not** part of the repository and
    their upstream licence was not recorded, so nothing here depends on them and no test
    asserts on them when they are absent. Real-face validation with the actual camera is a
    documented user step (docs/design/perception.md).
    """

    def _external(self, name: str) -> Path | None:
        path = Path(__file__).resolve().parents[2] / "data" / "models" / name
        return path if path.is_file() else None

    def test_optional_external_positive_control(self) -> None:
        import cv2

        if not face_backend_available("yunet"):
            self.skipTest(
                "YuNet model or cv2.FaceDetectorYN unavailable: put face_detection_yunet_2023mar.onnx "
                "into data/models/ and re-run (see docs/design/perception.md)"
            )
        path = self._external("lena.jpg")
        if path is None:
            self.skipTest("data/models/lena.jpg is not on this machine (optional positive control, not repo content)")
        image = cv2.imread(str(path))
        detector = YuNetFaceDetector(load_yunet_model_path(), (image.shape[1], image.shape[0]), DEFAULT_FACE_SCORE_THRESHOLD)
        self.assertGreaterEqual(detector.detect(image), 1)

    def test_face_rig_is_detected_by_yunet_when_available(self) -> None:
        """The generated face rig (no licence, ships with the test) drives the face path."""
        if not face_backend_available("yunet"):
            self.skipTest("YuNet unavailable")
        scene = np.full((480, 640, 3), 70, np.uint8)
        face = rig_face()
        scene[20 : 20 + face.shape[0], 40 : 40 + face.shape[1]] = face
        detector = YuNetFaceDetector(load_yunet_model_path(), (640, 480), DEFAULT_FACE_SCORE_THRESHOLD)
        self.assertGreaterEqual(detector.detect(scene), 1)

    def test_face_confirmation_drives_presence_on_the_face_scene(self) -> None:
        if not face_backend_available("yunet"):
            self.skipTest("YuNet unavailable")
        captured = run_script(face_track(60) + still_track(120, fill=70), detector="yunet", **FIELD_THRESHOLDS)
        self.assertEqual(captured.states, [ABSENT, PRESENT, ABSENT])
        self.assertGreater(captured.summary["counters"]["frames_with_face"], 0)


class CameraBackendTests(unittest.TestCase):
    """`default_backend()` must be right on **both** platforms, not only the one running the suite.

    Why this exists: the backend used to be the module constant `int(cv2.CAP_DSHOW)`. That value is
    a *Windows* fact — on the original dev machine MSMF fails instantly and DSHOW was the only
    backend that opened the Chicony camera — but it was written as a platform-independent constant.
    `cv2.CAP_DSHOW` is still *defined* on Linux, so the failure was not an ImportError or a clear
    "unsupported backend" error: the camera simply reported `isOpened() == False` on a machine whose
    camera worked fine (measured 2026-10-08 on WSL2 with a 2K USB Camera over `usbipd`).
    The Linux port could not have caught it — that machine had no camera to try.

    Both branches are asserted on purpose, so that whichever platform runs `npm test`, the *other*
    mapping is exercised too and neither can rot unnoticed.
    """

    def test_windows_uses_dshow(self) -> None:
        self.assertEqual(default_backend("win32"), int(cv2.CAP_DSHOW))

    def test_posix_uses_v4l2(self) -> None:
        for platform in ("linux", "darwin", "freebsd13"):
            with self.subTest(platform=platform):
                self.assertEqual(default_backend(platform), int(cv2.CAP_V4L2))

    def test_module_default_and_config_follow_the_rule_for_this_platform(self) -> None:
        # The constant drifting away from the function *is* the defect; assert they agree, and that
        # a default-constructed CameraConfig picks it up (both run.py call sites rely on that).
        from perception_edge import camera as camera_module

        self.assertEqual(camera_module.DEFAULT_BACKEND, default_backend(sys.platform))
        self.assertEqual(CameraConfig().backend, camera_module.DEFAULT_BACKEND)

    def test_default_backend_is_never_cap_any(self) -> None:
        # "Explicit rather than left to OpenCV": CAP_ANY would silently pick one.
        for platform in ("win32", "linux"):
            with self.subTest(platform=platform):
                self.assertNotEqual(default_backend(platform), int(cv2.CAP_ANY))

    def test_backend_name_names_the_backend_that_failed(self) -> None:
        # The old failure message said "backend=CAP_DSHOW" whatever the configured backend was.
        self.assertEqual(backend_name(int(cv2.CAP_DSHOW)), "CAP_DSHOW")
        self.assertEqual(backend_name(int(cv2.CAP_V4L2)), "CAP_V4L2")
        self.assertEqual(backend_name(int(cv2.CAP_ANY)), "CAP_ANY")

    def test_default_config_requests_mjpg(self) -> None:
        # Not cosmetic: uncompressed YUYV at 640x480 is ~614 KB/frame and over a virtual USB link
        # that costs ~205-225 ms/frame (~4.5 fps) where MJPG costs ~30 ms (~32 fps). The real-camera
        # path refuses below 20 fps, so a missing MJPG request reads as "the camera is too slow".
        self.assertEqual(CameraConfig().fourcc, "MJPG")

    def test_negotiated_fourcc_is_read_back_not_assumed(self) -> None:
        # The request is best-effort; the report must show what the driver actually settled on.
        class _FakeCapture:
            def __init__(self, value: int) -> None:
                self._value = value

            def get(self, _prop: int) -> float:
                return float(self._value)

        self.assertEqual(negotiated_fourcc(_FakeCapture(cv2.VideoWriter_fourcc(*"MJPG"))), "MJPG")  # type: ignore[arg-type]
        self.assertEqual(negotiated_fourcc(_FakeCapture(cv2.VideoWriter_fourcc(*"YUYV"))), "YUYV")  # type: ignore[arg-type]
        self.assertEqual(negotiated_fourcc(_FakeCapture(0)), "", "驱动不报格式时给空串，不编一个")  # type: ignore[arg-type]


def _presence_input(**overrides):
    from perception_edge.contracts import PresenceEventInput

    values = {"present": True, "confidence": 0.9, "source_detail": "test"}
    values.update(overrides)
    return PresenceEventInput(**values)


class LiveModeConfigTests(unittest.TestCase):
    """`--live` must actually run unbounded, and this is the config it runs with.

    Why this exists (measured 2026-10-08): the live block in `main()` set `parsed["seconds"] = 0.0`
    **after** `cfg = RunConfig(**parsed)` had already been built, so the mutation reached nobody.
    `cfg.seconds` kept the `--seconds` default of 20 and `run()` stopped the loop on schedule —
    the page's preview child exited with code 0 after 161 frames at 8 fps (about 20.1 s) while the
    page still showed 「运行中」 and the picture simply froze. The module docstring had promised the
    opposite all along ("The live loop has no `--seconds`"), so no reader could see the bug either.

    `run()` is replaced rather than executed: the assertion is about the config live mode hands to
    it, which needs no camera, no frames and no 20 seconds of waiting. Runs before the fix:
    `seconds` is 20.0 and this test fails.
    """

    def test_live_mode_hands_run_an_unbounded_config(self) -> None:
        from perception_edge import run as run_module

        captured: dict[str, object] = {}

        def fake_run(cfg, emitter, on_frame=None, should_stop=None, pace_fps=None):  # noqa: ANN001
            captured["cfg"] = cfg
            captured["pace_fps"] = pace_fps
            captured["on_frame"] = on_frame
            captured["should_stop"] = should_stop
            return {"stopped": "test"}

        original = run_module.run
        run_module.run = fake_run
        try:
            exit_code = run_module.main(["--live", "--source", "synthetic", "--scenario", "empty-room"])
        finally:
            run_module.run = original

        self.assertEqual(exit_code, 0)
        cfg = captured["cfg"]
        # The whole point: no time cap. 0 means "no limit" to the loop's own check.
        self.assertEqual(cfg.seconds, 0.0, "live 模式不能被 --seconds 的默认值截断")
        self.assertIsNone(cfg.max_frames, "也不该有帧数上限")
        self.assertTrue(cfg.quiet_frames, "逐帧记录会淹掉 stdout，live 模式必须安静")
        self.assertEqual(captured["pace_fps"], 8.0, "live 模式按 --live-fps 走（默认 8）")
        self.assertIsNotNone(captured["should_stop"], "停止条件必须交出去（stdin 关闭即退出）")

    def test_a_timed_run_keeps_its_cap(self) -> None:
        """The counterfactual: the fix must not turn *every* run unbounded."""
        from perception_edge import run as run_module

        captured: dict[str, object] = {}

        def fake_run(cfg, emitter, on_frame=None, should_stop=None, pace_fps=None):  # noqa: ANN001
            captured["cfg"] = cfg
            captured["pace_fps"] = pace_fps
            return {"stopped": "test"}

        original = run_module.run
        run_module.run = fake_run
        try:
            run_module.main(["--source", "synthetic", "--scenario", "empty-room", "--seconds", "7"])
        finally:
            run_module.run = original

        self.assertEqual(captured["cfg"].seconds, 7.0, "带 --seconds 的普通运行仍然有上限")
        self.assertIsNone(captured["pace_fps"], "非 live 不按 fps 限速")


if __name__ == "__main__":
    unittest.main(verbosity=2)
